# Generated by Django 2.2.7 on 2019-12-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191127_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade')),
                ('preco', models.FloatField(default=0.0, verbose_name='Preço')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=20, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Locadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('endereco', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Endereco', verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoPorTemporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(default=0.0, verbose_name='Preço')),
                ('data_inicio_temporada', models.DateField(verbose_name='Data de Início')),
                ('data_fim_temporada', models.DateField(verbose_name='Data de Fim')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('data_reserva', models.DateField(verbose_name='Data de Reserva')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carro')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ReservaCarro', verbose_name='Reserva do Carrro')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaQuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('data_reserva', models.DateField(verbose_name='Data de Reserva')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('num_noites', models.DateField(verbose_name='Quantidade de Noites')),
            ],
        ),
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('max_ocupantes', models.IntegerField(verbose_name='Máximo de Ocupantes')),
                ('banheiro_compartilhado', models.BooleanField(verbose_name='Banheiro Compartilhado')),
            ],
        ),
        migrations.DeleteModel(
            name='Apartamento',
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='descricao_hotel',
        ),
        migrations.AddField(
            model_name='quarto',
            name='preco',
            field=models.FloatField(default=0.0, verbose_name='Preço'),
        ),
        migrations.DeleteModel(
            name='RecomendacaoHotel',
        ),
        migrations.AddField(
            model_name='reservaquarto',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Quarto'),
        ),
        migrations.AddField(
            model_name='reservapacote',
            name='reserva_quarto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ReservaQuarto', verbose_name='Reserva do Quarto'),
        ),
        migrations.AddField(
            model_name='precoportemporada',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoQuarto'),
        ),
        migrations.AddField(
            model_name='carro',
            name='locadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Locadora'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='endereco',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoQuarto'),
        ),
    ]
