# Generated by Django 2.2.7 on 2019-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191204_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaquarto',
            name='num_noites',
            field=models.IntegerField(verbose_name='Quantidade de Noites'),
        ),
    ]
