# Generated by Django 2.2.7 on 2019-12-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191204_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservapacote',
            name='reserva_carro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ReservaCarro', verbose_name='Reserva do Carro'),
        ),
    ]
